doc/PCEFTPOS-cloud/doc/Examples-master/Examples-master/PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PCEFTPOS.WebAPI.PosCloudAPITest.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

doc/PCEFTPOS-cloud/doc/Examples-master/Examples-master/PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async/Pages/Index.cshtml.cs
using System;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async.Model;
using PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async.Helpers;
using PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async.Interface;
using Newtonsoft.Json.Linq;

namespace PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async.Pages
{
    public class IndexModel : PageModel
    {
        private const int TRX_EXPIRATION_MINS = 3;
        private const int DOLLAR_TO_CENT = 100;
        private const int TRX_RND_STR_LENGTH = 16;

        /// <summary>
        /// App settings
        /// </summary>
        private AppSettings appSettings;

        /// <summary>
        /// Session repository
        /// </summary>
        private ISessionRepository sessionRepository;

        /// <summary>
        /// Http clients repository
        /// </summary>
        private IHttpClientRepository clients;

        /// <summary>
        /// Token
        /// </summary>
        private string token;

        public IndexModel(IOptions<AppSettings> appSettings, ISessionRepository sessionRepository, IHttpClientRepository clients)
        {
            token = string.Empty;

            this.appSettings = appSettings.Value;
            this.sessionRepository = sessionRepository;
            this.clients = clients;
            token = string.Empty;
        }

        /// <summary>
        /// Get token
        /// </summary>
        /// <returns>Return token response</returns>
        public async Task<TokenResponse> GetTokenAsync()
        {
            var authClient = clients.GetAuthClient();

            var url = new Uri(new Uri(appSettings.TokenServer), "tokens/cloudpos");
            var body = new TokenRequest()
            {
                PosId = new Guid(appSettings.PosId),
                PosName = appSettings.PosName,
                PosVersion = appSettings.PosVersion,
                Username = appSettings.PinpadUsername,
                Password = appSettings.PinpadPassword,
                PairCode = appSettings.PinpadPairCode
            };

            authClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

            var str = JsonConvert.SerializeObject(body);

            HttpContent content = new StringContent(JsonConvert.SerializeObject(body), UTF8Encoding.UTF8, "application/json");

            var res = await authClient.PostAsync(url, content);
            
            if (res.IsSuccessStatusCode)
            {
                var tokenResponse = await res.Content.ReadAsAsync<TokenResponse>();
                token = tokenResponse?.Token;
                return tokenResponse;
            }

            return null;
        }

        /// <summary>
        /// Make transaction
        /// </summary>
        /// <param name="amount">Amount of transaction</param>
        public async Task OnPostDoTransactionAsync(string amount)
        {
            var sessionId = Guid.NewGuid();
            var actualAmount = float.Parse(amount);

            var url = appSettings.Server + $"sessions/{sessionId}/transaction?async=true";

            // Create a sample json 'basket' object which is sent as part of transaction request 
            JObject basket = JObject.FromObject(
                new
                {
                    id = (Guid.NewGuid()).ToString(),
                    amt = 18700,
                    tax = 1760,
                    dis = 650,
                    sur = 374,
                    items = new dynamic[] 
                    {
                        new { id = "t39kq002", sku = "k24086723", qty = 2, amt = 2145, tax = 200, dis = 50, name = "XData USB Drive" },
                        new { id = "t39kq003", sku = "s23475697", qty = 1, amt = 8910, tax = 810, name = "MSoft OSuite", srl = "ms7843k346j23" },
                        new { id = "t39kq004", sku = "m47060855", qty = 5, amt = 1100, tax = 110, dis = 110, name = "A4 Notepad"}
                    }
                }
            );

            var request = new ApiRequest<EFTTransactionRequest>()
            {
                Request = new EFTTransactionRequest()
                {
                    TxnType = "P",
                    TxnRef = RandomStr.RandomString(TRX_RND_STR_LENGTH),
                    AmtPurchase = Convert.ToInt32(actualAmount * DOLLAR_TO_CENT),
                    Merchant = appSettings.Merchant,
                    Application = appSettings.Application,
                    Basket = basket
                },
                Notification = new Notification
                {
                    Uri = appSettings.NotificationUri
                }
            };
            
            if (string.IsNullOrEmpty(token))
            {
                token = (await GetTokenAsync())?.Token;
            }

            var apiClient = clients.GetAPIClient();
            apiClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            apiClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

            HttpContent content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");
            try
            {
                var activeTxn = new ActiveSession() { SessionId = sessionId.ToString(), Expire = DateTime.Now.AddMinutes(TRX_EXPIRATION_MINS).Ticks };
                await sessionRepository.AddSessionAsync(activeTxn);

                var response = await apiClient.PostAsync(url, content);
            }
            catch
            {
            }
        }

        /// <summary>
        /// Process button click on pinpad notification 
        /// </summary>
        /// <param name="key">Button key</param>
        public async Task OnPostSendKeyAsync([FromBody] EFTSendKeyRequest key)
        {
            if (key == null)
            {
                return;
            }

            var url = appSettings.Server + $"sessions/{key.SessionId}/sendkey";

            var request = new ApiRequest<EFTSendKeyRequest>()
            {
                Request = new EFTSendKeyRequest()
                {
                    Data = key.Data,
                    Key = key.Key
                },
                Notification = new Notification
                {
                    Uri = appSettings.NotificationUri
                }
            };
            
            if (string.IsNullOrEmpty(token))
            {
                token = (await GetTokenAsync())?.Token;
            }

            var apiClient = clients.GetAPIClient();
            apiClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            apiClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

            HttpContent content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");

            var response = await apiClient.PostAsync(url, content);
        }
    }
}

doc/PCEFTPOS-cloud/doc/Examples-master/Examples-master/PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async/Pages/Pinpad.cshtml.cs
using System;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async.Interface;
using PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async.Model;

namespace PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async.Pages
{
    public class PinpadModel : PageModel
    {
        //[BindProperty]
        //public EFTStatusResponse EFTStatusResponse { get; set; }

        //[BindProperty]
        //public EFTLogonResponse EFTLogonResponse { get; set; }

        private const int TRX_EXPIRATION_MINS = 3;
        private const int DOLLAR_TO_CENT = 100;
        private const int TRX_RND_STR_LENGTH = 16;

        /// <summary>
        /// App settings
        /// </summary>
        private AppSettings appSettings;

        /// <summary>
        /// Session repository
        /// </summary>
        private ISessionRepository sessionRepository;

        /// <summary>
        /// Http clients repository
        /// </summary>
        private IHttpClientRepository clients;

        /// <summary>
        /// Token
        /// </summary>
        private string token;


        public PinpadModel(IOptions<AppSettings> appSettings, ISessionRepository sessionRepository, IHttpClientRepository clients)
        {
            this.appSettings = appSettings.Value;
            this.sessionRepository = sessionRepository;
            this.clients = clients;
            token = string.Empty;
        }

        /// <summary>
        /// Get token
        /// </summary>
        /// <returns>Return token response</returns>
        public async Task<TokenResponse> GetTokenAsync()
        {
            var authClient = clients.GetAuthClient();

            var url = new Uri(new Uri(appSettings.TokenServer), "tokens/cloudpos");
            var body = new TokenRequest()
            {
                PosId = new Guid(appSettings.PosId),
                PosName = appSettings.PosName,
                PosVersion = appSettings.PosVersion,
                Username = appSettings.PinpadUsername,
                Password = appSettings.PinpadPassword,
                PairCode = appSettings.PinpadPairCode
            };

            authClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

            var str = JsonConvert.SerializeObject(body);

            HttpContent content = new StringContent(JsonConvert.SerializeObject(body), UTF8Encoding.UTF8, "application/json");

            var res = await authClient.PostAsync(url, content);
            
            if (res.IsSuccessStatusCode)
            {
                var tokenResponse = await res.Content.ReadAsAsync<TokenResponse>();
                token = tokenResponse?.Token;
                return tokenResponse;
            }

            return null;
        }

        /// <summary>
        /// Do pinpad logon
        /// </summary>
        public async Task OnPostDoLogonAsync()
        {
            var sessionId = Guid.NewGuid();

            var url = appSettings.Server + $"sessions/{sessionId}/logon?async=true";

            var request = new ApiRequest<EFTLogonRequest>()
            {
                Request = new EFTLogonRequest()
                {
                    LogonType = " ",
                    ReceiptAutoPrint = "0",
                    CutReceipt = "0",
                    Merchant = appSettings.Merchant,
                    Application = appSettings.Application
                },
                Notification = new Notification
                {
                    Uri = appSettings.NotificationUri
                }
            };

            if (string.IsNullOrEmpty(token))
            {
                token = (await GetTokenAsync())?.Token;
            }

            var apiClient = clients.GetAPIClient();
            apiClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            apiClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

            HttpContent content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");

            var response = await apiClient.PostAsync(url, content);
        }

        /// <summary>
        /// Get pinpad status
        /// </summary>
        public async Task OnPostDoStatusAsync()
        {
            var sessionId = Guid.NewGuid();

            var url = appSettings.Server + $"sessions/{sessionId}/status?async=true";

            var request = new ApiRequest<EFTStatusRequest>()
            {
                Request = new EFTStatusRequest()
                {
                    StatusType = "0",
                    Merchant = appSettings.Merchant,
                    Application = appSettings.Application
                },
                Notification = new Notification
                {
                    Uri = appSettings.NotificationUri
                }
            };

            //TODO: add or expired
            if (token == null || string.Equals(token, string.Empty))
            {
                //TODO: add check afterwords
                token = (await GetTokenAsync())?.Token;
            }

            var apiClient = clients.GetAPIClient();
            apiClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            apiClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

            HttpContent content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");

            var response = await apiClient.PostAsync(url, content);
        }

        /// <summary>
        /// Process button click on pinpad notification 
        /// </summary>
        /// <param name="key">Button key</param>
        public async Task OnPostSendKeyAsync([FromBody] EFTSendKeyRequest key)
        {
            if (key == null)
            {
                return;
            }

            var url = appSettings.Server + $"sessions/{key.SessionId}/sendkey";

            var request = new ApiRequest<EFTSendKeyRequest>()
            {
                Request = new EFTSendKeyRequest()
                {
                    Data = key.Data,
                    Key = key.Key
                },
                Notification = new Notification
                {
                    Uri = appSettings.NotificationUri
                }
            };

            if (string.IsNullOrEmpty(token))
            {
                token = (await GetTokenAsync())?.Token;
            }

            var apiClient = clients.GetAPIClient();
            apiClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            apiClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

            HttpContent content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");

            var response = await apiClient.PostAsync(url, content);
        }
    }
}

doc/PCEFTPOS-cloud/doc/Examples-master/Examples-master/PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

doc/PCEFTPOS-cloud/doc/Examples-master/Examples-master/PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async/Pages/Index.cshtml
@page
@model PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async.Pages.IndexModel
@{
    ViewData["Title"] = "Home page";
}

<br />

<div class="hoffset2-index">
    <h1 class="hoffset1-index voffset1-index">Test POS</h1>
    <form class="form-horizontal" autocomplete="off" method="post">
        <div class="col-md-12 container">
            <div class='col-md-1 bold-font box container no-left-padding'>Amount: </div>
            <div class='col-md-2 container'>
                <input type='text' id='inputAmount' class='form-control' name="amount" value="1.00" />
                <span id="errorAmt" class="text-danger"></span>
            </div>
        </div>
        <br /><br />
        <div class="col-md-12 container">
            <button type="submit" id="btnSubmit" class="btn btn-primary" asp-page-handler="DoTransaction">Transaction</button>
        </div>

    </form>
</div>


<br /><br /><br />

<div class="col-md-12 row hoffset3-index">
    <div id="divTransaction" class="col-md-6 container">
        <div>
            <label class="box one-line">Response Code: </label><label id="lblResCode" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Response Text: </label><label id="lblResText" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Reference: </label><label id="lblRef" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Transaction Type: </label><label id="lblTranType" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Amount: </label><label id="lblAmount" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Cash: </label><label id="lblCash" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Tip: </label><label id="lblTip" class="value one-line"></label>
        </div>
        <div id="divAvBal">
            <label class="box one-line">Available Balance: </label><label id="lblAvBal" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Card Account Type: </label><label id="lblAccType" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Card Name: </label><label id="lblCardName" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Card Type: </label><label id="lblCardType" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">CAID: </label><label id="lblCAID" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">CATID: </label><label id="lblCATID" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Date: </label><label id="lblDate" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Expiry Date: </label><label id="lblExpDate" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Merchant: </label><label id="lblMerchant" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Pan: </label><label id="lblPan" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">RRN: </label><label id="lblRRN" class="value one-line"></label>
        </div>
        <div>
            <label class="box one-line">Track 2: </label><label id="lblTrack2" class="value one-line"></label>
        </div>
    </div>
    <div id="divReceipt" class="col-md-6">
        <h4>Receipt</h4>
        <p id="txtReceipt" class="break-in-lines receipt-font"></p>
    </div>
</div>



<div class="modal fade" id="notificationModal" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body" id="divModalBody">
                <h3 id="txtContent0" class="text-center receipt-font"></h3>
                <h3 id="txtContent1" class="text-center receipt-font"></h3>
                <input id="txtAuth" class="form-control" type="text" />
            </div>
            <div class="modal-footer no-border">
                <div class="col-md-12 row modal-button-div">
                    <!--2nd button-->
                    <button id="btnClose" class="btn btn-primary modal-button pull-right"></button>
                    <!--1st button-->
                    <button id="btnAccept" class="btn btn-primary modal-button right-margin1 pull-right">Yes</button>
                </div>
            </div>
        </div>
    </div>
</div>


<script language="JavaScript" type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/signalr/signalr.js"></script>
<script src="~/js/config.js"></script>
<script src="~/js/transactionnotification.js"></script>

<style>
    .modal {
        width: 500px;
        margin: 0 auto;
    }

    .modal-content {
        width: 400px;
    }

    .no-left-padding {
        padding-left: 0px;
    }

    .no-border {
        border:none;
    }

    .hoffset1-index {
        padding-left: 13px;
    }

    .hoffset2-index {
        padding-left: 40px;
    }

    .hoffset3-index {
        padding-left: 55px;
    }

    .voffset1-index {
        margin-top: 0px;
    }

    button {
        width: 100px;
    }

    .right-margin1 {
        margin-right: 5px;
    }

    .box {
        display: flex;
        align-items: center;
        height: 30px;
    }

    .bold-font {
        font-weight: bold;
    }

    .value {
        margin-left: 5px;
        font-weight: normal;
    }

    .one-line {
        display: inline-block;
        float: none;
    }

    .break-in-lines {
        white-space: pre-wrap;
    }

    .receipt-font {
        font-family: "Courier New", Courier, monospace;
    }

    #btnAccept, #btnClose, #divTransaction, #divReceipt, #txtAuth {
        display: none;
    }

    body.modal-open div.modal-backdrop {
        z-index: 1;
    }
</style>

doc/PCEFTPOS-cloud/doc/Examples-master/Examples-master/PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async/Pages/Pinpad.cshtml
@page
@model PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async.Pages.PinpadModel
@{
    ViewData["Title"] = "Pinpad";
}

<br />
<div class="hoffset1-pinpad">
    <form method="post">
        <h1 class="voffset1-pinpad voffset2-pinpad">Pinpad</h1>
        <button type="submit" class="btn btn-primary hoffset2-pinpad" asp-page-handler="DoStatus">Get Status</button>
        <button type="submit" class="btn btn-primary" asp-page-handler="DoLogon">Logon</button>
    </form>



    <br />

    <div class="col-md-12 row no-left-padding">
        <div id="divStatus" class="col-md-6 container">
            <div>
                <label class="box one-line">Response Code: </label><label id="lblResponseCode" class="value one-line"></label>
            </div>
            <div>
                <label class="box one-line">Response Text: </label><label id="lblResponseText" class="value one-line"></label>
            </div>
            <div>
                <label class="box one-line">PINPad Version: </label><label id="lblPinPadVersion" class="value one-line"></label>
            </div>
            <div>
                <label class="box one-line">PINPad Serial: </label><label id="lblPinPadSerialNumber" class="value one-line"></label>
            </div>
        </div>

        <div id="divLogon" class="col-md-6 container">
            <div>
                <label class="box one-line">Response Code: </label><label id="lblResponseCode" class="value one-line"></label>
            </div>
            <div>
                <label class="box one-line">Response Text: </label><label id="lblResponseText" class="value one-line"></label>
            </div>
        </div>

        <div id="divReceipt" class="col-md-6">
            <h4>Receipt</h4>
            <p id="txtReceipt" class="break-in-lines receipt-font"></p>
        </div>
    </div>
</div>

<div class="modal fade" id="notificationModal" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body" id="divModalBody">
                <h3 id="txtContent0" class="text-center receipt-font"></h3>
                <h3 id="txtContent1" class="text-center receipt-font"></h3>
            </div>
            <div class="modal-footer no-border">
                <div class="col-md-12 row modal-button-div">
                    <button id="btnClose" class="btn btn-primary modal-button pull-right"></button>
                </div>
            </div>
        </div>
    </div>
</div>

<script language="JavaScript" type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/signalr/signalr.js"></script>
<script src="~/js/config.js"></script>
<script src="~/js/pinpadnotification.js"></script>

<style>
    .modal {
        width: 500px;
        margin: 0 auto;
    }

    .modal-content {
        width: 400px;
    }

    button {
        width: 100px;
    }

    .hoffset1-pinpad {
        padding-left: 50px;
    }

    .hoffset2-pinpad {
        margin-right: 20px;
    }

    .voffset1-pinpad {
        margin-top: 0px;
    }

    .voffset1-pinpad {
        margin-bottom: 20px;
    }

    .value {
        margin-left: 5px;
        font-weight: normal;
    }

    .one-line {
        display: inline-block;
        float: none;
    }

    .break-in-lines {
        white-space: pre-wrap;
    }

    .receipt-font {
        font-family: "Courier New", Courier, monospace;
    }

    .no-border {
        border: none;
    }

    .no-left-padding {
        padding-left: 0px;
    }

    #btnAccept, #btnClose, #divStatus, #divReceipt, #divLogon {
        display: none;
    }
</style>

doc/PCEFTPOS-cloud/doc/Examples-master/Examples-master/PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PCEFTPOS.WebAPI.PosCloudAPITest.RazorPages.Async</title>

    <link rel="stylesheet" href="~/css/simple-sidebar.css">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <style>
        #wrapper #sidebar-wrapper {
            width: 50px;
        }

        #wrapper .sidebar-nav {
            display: none;
        }

        #wrapper.toggled .sidebar-nav {
            display: block;
        }

        a#menu-toggle {
            display: inline-block;
            width: 100%;
            line-height: 100%;
            padding: 0;
            margin: 0;
            color: #999999;
            text-align: right;
            padding-right: 20px;
            padding-top: 20px;
        }

        .voffset1-nav {
            padding-top: 0px;
        }

        .voffset2-nav {
            margin-top: 50px;
        }

        .hoffset1-nav {
            padding-right: 10px;
        }

        .hoffset2-nav {
            padding-left: 50px;
        }

        .medium-font {
            font-size: 20px;
        }

        .menuitem-height {
            height: 50px;
        }
    </style>
</head>
<body class="voffset1-nav">
    <div id="wrapper" class="toggled">
        <div id="sidebar-wrapper">
            <a id="menu-toggle" href="#menu-toggle" class="btn btn-secondary toggle-button">
                <span id="main_icon" class="navbar-icon fa fa-bars icon medium-font">
                </span>
            </a>
            <ul class="sidebar-nav voffset2-nav">
                <li class="sidebar-brand menuitem-height">
                    <a asp-page="/Index" class="navbar-brand">
                        <span class="fa fa-home hoffset1-nav">
                        </span> <span>Home</span>
                    </a>
                </li>
                <li class="sidebar-brand menuitem-height">
                    <a asp-page="/Pinpad" class="navbar-brand">
                        <span class="fa fa-calculator hoffset1-nav">
                        </span> <span>Pinpad</span>
                    </a>
                </li>
            </ul>
        </div>

        <div id="page-content-wrapper voffset1-nav hoffset2-nav">
            <div class="container-fluid">
                @RenderBody()
            </div>
            <footer></footer>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        $(document).ready(function () {
            $("#menu-toggle").click(function (e) {
                e.preventDefault();
                $("#wrapper").toggleClass("toggled");
            });
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>